SCREEN_WIDTH = 1600
SCREEN_HEIGHT = 900
SCREEN_TITLE = "Boat Frenzy"
SCALE = 4
RIGHT_FACING = 0
LEFT_FACING = 1

BACKGROUNDS_LAYER = "Backgrounds"
BOAT_LAYER = "Boat"
DANGERS_LAYER = "Dangers"
GEMS_LAYER = "Gems"
PROJECTILES_LAYER = "Projectiles"
ALL_LAYERS = (BACKGROUNDS_LAYER, PROJECTILES_LAYER, DANGERS_LAYER, GEMS_LAYER, BOAT_LAYER)  # In order