SCREEN_WIDTH = 1664
SCREEN_HEIGHT = 936
SCREEN_TITLE = "Boat Frenzy"
SCALE = 4
RIGHT_FACING = 0
LEFT_FACING = 1

BOAT_LAYER = "Boat"
DANGERS_LAYER = "Dangers"
GEMS_LAYER = "Gems"
ALL_LAYERS = (DANGERS_LAYER, GEMS_LAYER, BOAT_LAYER)  # In order